# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ff49d71035febb25205c2ff0e435845c"
name = "Kites"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
scopes = "read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_files,write_files"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
